movies = ["Toy Story series","Harry Potter series","The Lion King","Frozen series","Spider-Man: Into the Spider-Verse","The Incredibles series","Percy Jackson series","Shrek series","The Hunger Games series","Despicable Me series","Finding Nemo series","Monsters, Inc. series","Kung Fu Panda series","How to Train Your Dragon series","Tangled","Moana","Zootopia","Big Hero 6","Wreck-It Ralph series"]
books = ["Harry Potter series","Percy Jackson & the Olympians series","The Hunger Games series","The Chronicles of Narnia series","Diary of a Wimpy Kid series","Charlotte's Web","Matilda","The BFG","The Gruffalo","Where the Wild Things Are","The Tale of Peter Rabbit","The Wind in the Willows","Anne of Green Gables","The Secret Garden","Alice's Adventures in Wonderland","The Hobbit","Lord of the Flies","To Kill a Mockingbird","The Giver","Holes","Bridge to Terabithia","Wonder"]
intresser = ["Maling","Tegning","Fotografering","Lesing","Strikking","Heikling","Synging","Spille et musikkinstrument","Skulpturering","Treverk","Matlaging","Baking","Jogging","Wandern","Fjellklatring","Fisking","Sykling","Svømming","Dykking","Surfing","Yoga","Meditasjon","Skuespill","Dansing","Skating","Skateboarding","Golf","Tennis","Fotball","Basketball","Volleyball","Bordspill","Puslespill","Kortspill","Dataspill","Modellbygging","Origami","Kalligrafi","Skjønnlitterær skriving","Poesi","Gartneri","Fugletitting","Astronomi","Frimerkesamling","Myntsamling","Reising","Språklæring","Podcasting","Bloggskriving","Digital kunst","Droneflyging","Kampsport"]
norwegianCounties = ["Akershus","Aust-Agder","Buskerud","Finnmark","Hedmark","Hordaland","Møre og Romsdal","Nordland","Oppland","Oslo","Rogaland","Sogn og Fjordane","Telemark","Troms","Trøndelag","Vest-Agder","Vestfold","Østfold"]

norwegianLivingConditions = ["Bysentrum","Forsteder","Landsbygd","Småby","Fjellområder","Kystområder","Øy","Skogsområder","Flatlands"]
Influencers = ["PewDiePie","MrBeast","JoJo Siwa","Dixie D'Amelio","Charli D'Amelio","TommyInnit","Dream","Ryan's World","Unspeakable","FGTeeV","Flamingo","James Charles","Addison Rae","Brent Rivera","David Dobrik","KSI","Troom Troom","5-Minute Crafts","Zach King","Loren Gray","Lele Pons","King Bach","Logan Paul","Jake Paul","Kylie Jenner","Emma Chamberlain","Zoe Laverne","Spencer X","Bella Poarch","Will Smith","Chris Hemsworth","Dwayne 'The Rock' Johnson","Selena Gomez","Ariana Grande","Billie Eilish"]


girl_names = ["Emma","Nora","Sofie","Olivia","Emilie","Leah","Sara","Maria","Amalie","Oda","Ida","Frida","Maja","Ingrid","Anna","Julie","Selma","Isabella","Ella","Elise","Alma","Tuva","Live","Mathea","Jenny","Vilde","Helene","Karoline","Linnea","Victoria"]
boy_names = ["Oliver","Emil","Oscar","William","Lucas","Mathias","Filip","Oskar","Jakob","Max","Benjamin","Isak","Jonas","Alexander","Magnus","Johannes","Daniel","Martin","Samuel","Sebastian","Adrian","Markus","Sander","Viktor","Kristian","Leo","David","Matheo","Sigurd","Fredrik"]
last_names = ["Hansen","Johansen","Olsen","Larsen","Andersen","Pedersen","Nilsen","Kristiansen","Jensen","Karlsen","Johnsen","Pettersen","Eriksen","Berg","Haugen","Hagen","Johannessen","Andreassen","Jacobsen","Dahl","Jørgensen","Halvorsen","Henriksen","Paulsen","Lund","Sørensen","Jakobsen","Moen","Iversen","Strand"]